package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/prjvvl/agen/platform/gen/agen/v1/agenv1connect"
	"github.com/prjvvl/agen/platform/internal/apidesc"
	"github.com/prjvvl/agen/platform/internal/hub"
)

// The reference pages are generated from the CLI's help and the API
// descriptors, so they cannot drift. Regenerate after a change with:
//
//	AGEN_UPDATE_DOCS=1 go test ./internal/cli -run TestReferenceDocs
func TestReferenceDocs(t *testing.T) {
	root := repoRoot()
	for rel, want := range map[string]string{
		"docs/reference/cli.md": cliReference(),
		"docs/reference/api.md": apiReference(t),
	} {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if os.Getenv("AGEN_UPDATE_DOCS") == "1" {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if strings.ReplaceAll(string(got), "\r\n", "\n") != want {
			t.Errorf("%s is out of date: run AGEN_UPDATE_DOCS=1 go test ./internal/cli -run TestReferenceDocs", rel)
		}
	}
}

var usageCommand = regexp.MustCompile(`^  agen ((?:[a-z][a-z-]*)(?: [a-z][a-z-]*)?)`)

func cliReference() string {
	var b strings.Builder
	b.WriteString("# CLI reference\n\n<!-- Generated by TestReferenceDocs in platform/internal/cli; do not edit. -->\n\n")
	b.WriteString("Fleet commands talk to the Hub in `--hub`/`--token` (or `AGEN_HUB`/`AGEN_TOKEN`), else to the local `agen up`.\n\n")
	b.WriteString("```text\n" + topUsage + "```\n")
	seen := map[string]bool{}
	for _, line := range strings.Split(topUsage, "\n") {
		m := usageCommand.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		cmd := strings.Fields(m[1])
		switch cmd[0] {
		case "hub", "nest", "token":
		default:
			cmd = cmd[:1]
		}
		name := strings.Join(cmd, " ")
		if seen[name] || name == "version" {
			continue
		}
		seen[name] = true
		var out, errOut safeBuf
		Main(context.Background(), append(cmd, "-h"), &out, &errOut)
		help := strings.TrimRight(out.String()+errOut.String(), "\n")
		fmt.Fprintf(&b, "\n## agen %s\n\n```text\n%s\n```\n", name, help)
	}
	return b.String()
}

func apiReference(t *testing.T) string {
	sd, err := apidesc.Service(agenv1connect.HubServiceName)
	if err != nil {
		t.Fatal(err)
	}
	var b strings.Builder
	b.WriteString("# API reference\n\n<!-- Generated by TestReferenceDocs in platform/internal/cli; do not edit. -->\n\n")
	b.WriteString("Every method is served by the Hub three ways, with the same token scopes and results:\n\n")
	b.WriteString("- **REST/JSON**: `POST /agen.v1.HubService/<Method>` with a JSON body and `Authorization: Bearer <token>`.\n")
	b.WriteString("- **gRPC / Connect**: service `agen.v1.HubService` (`spec/proto/agen/v1/hub.proto`).\n")
	b.WriteString("- **MCP**: tool `<snake_case name>` at `/mcp` (streamable HTTP).\n\n")
	b.WriteString("Fields use protojson names; `bytes` are base64; 64-bit integers may be strings.\n")
	for _, tl := range apidesc.Tools(sd) {
		m := tl.Method
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", m.Name(), tl.Description)
		fmt.Fprintf(&b, "Scope: `%s` · REST: `POST %s` · MCP tool: `%s`\n", hub.RequiredScope(string(m.Name())), tl.Procedure, tl.Name)
		fields := m.Input().Fields()
		if fields.Len() == 0 {
			continue
		}
		b.WriteString("\n| Field | Type | Description |\n|---|---|---|\n")
		for i := 0; i < fields.Len(); i++ {
			f := fields.Get(i)
			desc, _ := fieldDescription(f)
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", f.JSONName(), fieldType(f), strings.ReplaceAll(desc, "|", "\\|"))
		}
	}
	return b.String()
}

func fieldDescription(f protoreflect.FieldDescriptor) (string, bool) {
	loc := f.ParentFile().SourceLocations().ByDescriptor(f)
	c := strings.Join(strings.Fields(loc.LeadingComments), " ")
	return c, c != ""
}

func fieldType(f protoreflect.FieldDescriptor) string {
	if f.IsMap() {
		return "map&lt;" + fieldKind(f.MapKey()) + ", " + fieldKind(f.MapValue()) + "&gt;"
	}
	if f.IsList() {
		return "list of " + fieldKind(f)
	}
	return fieldKind(f)
}

func fieldKind(f protoreflect.FieldDescriptor) string {
	switch f.Kind() {
	case protoreflect.MessageKind:
		return string(f.Message().Name())
	case protoreflect.EnumKind:
		return string(f.Enum().Name())
	}
	return f.Kind().String()
}
